# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcVZKnfBHuRDRL4yzGXUmf4UtAD5BeJY
"""

!pip install textblob
!python -m textblob.download_corpora

from textblob import TextBlob

def analyze_text_sentiment(text):
  analysis = TextBlob(text)
  if analysis.sentiment.polarity > 0:
    return "Positive"
  elif analysis.sentiment.polarity < 0:
    return "Negative"
  else:
    return "Neutral"

text1 = "I absolutely love this movie! It was fantastic."
text2 = "The customer service was terrible and I'm very unhappy."
text3 = "The sky is blue today."
text4 = "I'm feeling a bit down."

print(f"'{text1}' - Sentiment: {analyze_text_sentiment(text1)}")
print(f"'{text2}' - Sentiment: {analyze_text_sentiment(text2)}")
print(f"'{text3}' - Sentiment: {analyze_text_sentiment(text3)}")
print(f"'{text4}' - Sentiment: {analyze_text_sentiment(text4)}")